### ISSUE TITLE
Incorrect/unnecessary bounds when deriving `IntoIterator`

### ISSUE THREAD

**Issue by tmillr** [JelteF/derive_more#347] opened 2024-04-15 11:22 UTC
### Input

```rust
#[derive(derive_more::IntoIterator)]
struct Struct<T> {
    #[into_iterator(owned, ref)]
    arr: [T; 2],
}
```

### Output

> Note the unnecessary bounds on the generic type parameter (which is used as the type of the array's ***elements***)

```rust
impl<T: ::core::iter::IntoIterator> ::core::iter::IntoIterator for Struct<T> {
    type Item = <[T; 2] as ::core::iter::IntoIterator>::Item;
    type IntoIter = <[T; 2] as ::core::iter::IntoIterator>::IntoIter;
    #[inline]
    fn into_iter(self) -> Self::IntoIter {
        <[T; 2] as ::core::iter::IntoIterator>::into_iter(self.arr)
    }
}

impl<'__deriveMoreLifetime, T> ::core::iter::IntoIterator
for &'__deriveMoreLifetime Struct<T>
where
    &'__deriveMoreLifetime T: ::core::iter::IntoIterator,
{
    type Item = <&'__deriveMoreLifetime [T; 2] as ::core::iter::IntoIterator>::Item;
    type IntoIter = <&'__deriveMoreLifetime [T; 2] as ::core::iter::IntoIterator>::IntoIter;
    #[inline]
    fn into_iter(self) -> Self::IntoIter {
        <&'__deriveMoreLifetime [T; 2] as ::core::iter::IntoIterator>::into_iter(
            &self.arr,
        )
    }
}
```

---

There should be no bounds necessary when the type of the field is an array or slice?

In the meantime, is there any way to specify bounds manually?

**Comment by tyranron** [comment] 2024-04-15 12:27
This is a duplicate of https://github.com/JelteF/derive_more/issues/208.

@tmillr this should work OK on [1.0.0-beta.6](https://docs.rs/derive_more/1.0.0-beta.6/derive_more/index.html). Try it out!

We already have the [test for that](https://github.com/JelteF/derive_more/blob/v1.0.0-beta.6/tests/into_iterator.rs#L91-L107). It's expansion is the following:
```rust
#[automatically_derived]
impl<T> derive_more::IntoIterator for Generic1<T> where Vec<T>: derive_more::IntoIterator {
    type Item = <Vec<T> as derive_more::IntoIterator>::Item;
    type IntoIter = <Vec<T> as derive_more::IntoIterator>::IntoIter;
    #[inline]
    fn into_iter(self) -> Self::IntoIter { <Vec<T> as derive_more::IntoIterator>::into_iter(self.items) }
}
#[automatically_derived]
impl<'__deriveMoreLifetime, T, > derive_more::IntoIterator for &'__deriveMoreLifetime Generic1<T> where &'__deriveMoreLifetime Vec<T>: derive_more::IntoIterator {
    type Item = <&'__deriveMoreLifetime Vec<T> as derive_more::IntoIterator>::Item;
    type IntoIter = <&'__deriveMoreLifetime Vec<T> as derive_more::IntoIterator>::IntoIter;
    #[inline]
    fn into_iter(self) -> Self::IntoIter { <&'__deriveMoreLifetime Vec<T> as derive_more::IntoIterator>::into_iter(&self.items) }
}
#[automatically_derived]
impl<'__deriveMoreLifetime, T, > derive_more::IntoIterator for &'__deriveMoreLifetime mut Generic1<T> where &'__deriveMoreLifetime mut Vec<T>: derive_more::IntoIterator {
    type Item = <&'__deriveMoreLifetime mut Vec<T> as derive_more::IntoIterator>::Item;
    type IntoIter = <&'__deriveMoreLifetime mut Vec<T> as derive_more::IntoIterator>::IntoIter;
    #[inline]
    fn into_iter(self) -> Self::IntoIter { <&'__deriveMoreLifetime mut Vec<T> as derive_more::IntoIterator>::into_iter(&mut self.items) }
}
```

**Closed by tyranron** 2024-04-15 12:27 UTC
Labels: bug, duplicate
