### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by dignifiedquire** [JelteF/derive_more#259] opened 2023-05-10 06:57 UTC
Hey I was wondering if it was possible to cut a release with the current code as there are some things I would love to start using. Thanks

**Comment by cwfitzgerald** [comment] 2023-07-05 23:24
Seconding this for the upgrade for `syn` 2.0. This is one of the lingerers.

**Comment by dignifiedquire** [comment] 2023-07-10 08:59
Because I couldn't wait I have published a fork, directly from todays `main` branch: https://crates.io/crates/derive_more_preview

**Comment by ilslv** [comment] 2023-07-10 09:16
@dignifiedquire maybe for some reason this won't work for you, but you can just add git dependency on a specific commit. So current latest `main` will look like:

```toml
derive_more = { git = "https://github.com/JelteF/derive_more.git", rev = "60ed1e7" }
```

**Comment by dignifiedquire** [comment] 2023-07-10 10:32
@ilslv thanks, that's what I have been doing for a while, but I need to cut releases and publish them to crates.io which does not allow to have git dependencies.

**Comment by JelteF** [comment] 2023-07-23 19:20
I published v1.0.0-beta.1 a few minutes ago from the current master. There's still a few breaking changes incoming before the final 1.0.0 release, but most things should stay the same now. Feedback is very much appreciated.

**Comment by dignifiedquire** [comment] 2023-07-24 08:52
great, thanks a lot!

**Comment by tyranron** [comment] 2023-08-10 14:44
@JelteF some report on integrating `1.0.0-beta.3` in our codebase.

<img width="381" alt="Screenshot 2023-08-10 at 16 25 25" src="https://github.com/JelteF/derive_more/assets/7114909/a9f259d4-e035-4e3e-8b89-513f465c588f">

### Bugs

Only 3 bugs were discovered during integration: #287, #288, #289   
Everything else worked out very well. Legacy syntax diagnostics were really very helpful.

### Inconveniences

Importing via `derive_more::Trait` both macro and trait at the same time was really helpful most of the time, except the one major case: `derive(Error)`.

It turned out that the case for defining `pub struct Error`/`pub enum Error`/`pub type Error` is very often one. We had tons of such errors in granular modules (like `transcoding::Error`, `command::create_user::Error`, etc), and, as the result, the tons of conflicts with `use derive_more::Error` imports. This lead to a quite refactoring, where in most cases such error types were renamed more precisely, depending on use-case. However, there are still enough places where such renaming is inappropriate or undesired, so we were forced to use `use derive_more::Error as StdError` imports there, which turned out to be a good practice, though, as it removed any ambiguities regarding ``[`Error`]`` references in docs.

However, I think the [`derive_more::macros` module re-exporting macros only](https://github.com/JelteF/derive_more/pull/273#discussion_r1271375050) would still make sense and may save some nerves for somebody in similar situations. Importing `derive_more-impl` crate alongside didn't really feel as an option. It's much easier to just write `use derive_more::macros::Error` in such a situation and don't bother with conflicts or dependencies.

### Happiness

Where `1.0.0-beta.3` `derive_more` really shines is `derive_more::Debug`, of course. It so much flexible and convenient, that allowed us to strip out every single manual `Debug` implementation in our codebase! Tons of boilerplate just gone away! Even more, no more `#[allow(missing_debug_implementations)]` are present in our codebase: very complicated places where we were just too lazy to write manual `impl`s became as easy as putting 2-3 attributes.

**Comment by JelteF** [comment] 2023-08-10 18:27
> Importing via derive_more::Trait both macro and trait at the same time was really helpful most of the time, except the one major case: derive(Error).

Hmm, that indeed sounds really annoying. Do you also have examples where re-exporting the traits did reduce the amount of imports you needed? If so, did you have any cases where it was beneficial that `Error` was exported. This is most certainly something we should fix before the final 1.0.0 release. 

I think maybe we shouldn't export the Error trait for this reason as an exception to the rule. I don't think any of the other derives have this problem that it's common for people to define a struct themselves with same name. `Error` seems like a special case in this regard. Having `use derive_more::Error` cause such breakage seems quite undesirable.

**Comment by tyranron** [comment] 2023-08-10 20:33
@JelteF 

> Do you also have examples where re-exporting the traits did reduce the amount of imports you needed?

Yes, most of the time, it reduced duplicated imports from `std`, and it felt like better ergonomics.

> If so, did you have any cases where it was beneficial that `Error` was exported.

Similar for the `Error`. There were quite a lot places where redundant `use std::error::Error` or `use std::error::Error as _`  were removed.

> I think maybe we shouldn't export the Error trait for this reason as an exception to the rule.

> `Error` seems like a special case in this regard.

I don't think so. That was my first feeling, of course, when I started the refactoring and was overwhelmed with a lot of import conflicts. But after finishing it, I think that things are much better the way they are now.

You see, I can't say the problem is with the new version of `derive_more`. For me, it seems quite the opposite: the problem is with the old version of `derive_more` and the new version just uncovers it. We had quite a lot of modules in the code which looked like this (or similar):
```rust
use std::error::Error as StdError;

use derive_more::{Display, Error};

#[derive(Display, Error)]
pub struct Error(Box<dyn StdError>);
```
So in the same scope we had `macro@Error` referring to `derive_more::Error`, local `Error` type, and the `std::error::Error` renamed as `StdError`, which was quite a bad situation, because the same ident `Error` referred to different things, while the same thing actually was named differently (`Error` and `StdError` at the same time). This lead to additional headache in docs: disambiguating stuff explicitly (``[`Error`](struct@Error)``). This mess appeared because old `derive_more` was allowing it easily.

With new `derive_more`, we streamlined such modules as the following:
```rust
use derive_more::{Display, Error as StdError};

#[derive(Display, StdError)]
pub struct Error(Box<dyn StdError>);
```
And voilà, no ambiguity anymore! No additional docs squatting!

So, I think the new `derive_more` forces to write better code, which is good. I don't want to lose this quality.

For those who are really pissed off and don't bother with such stuff, I really think the `use derive_more::macros::Error` re-export is enough to do the trick.

**Comment by JelteF** [comment] 2023-08-10 21:31
Okay, sounds good. Can you create a PR for the `macros` module? Or probably call it the `derives` module instead? (I slightly prefer that name)

**Comment by pacak** [comment] 2023-08-13 15:06
Did you mean to close this whole issue? #290 added a derive module, but I don't see a new release yet.

**Comment by KillingSpark** [comment] 2024-03-31 22:21
Any blockers for the release? Having syn 2.0 would be very nice

**Comment by tyranron** [comment] 2024-04-04 10:49
@KillingSpark yes, there are some blocker still for going fully into 1.0. Mostly are #142 and #328, but there can be some new ones once the code is revisited before 1.0.

Nevertheless, you already can use `syn` 2.0 by using [`1.0.0-beta.*` versions](https://docs.rs/derive_more/1.0.0-beta.6/derive_more/index.html).

**Comment by JelteF** [comment] 2024-06-15 14:30
Thanks to the work of @bash syn 2.0 support is now backported to the 0.99 branch too, as version 0.99.18

**Comment by JelteF** [comment] 2024-07-01 15:14
Closing this now that we have both beta releases an a syn 2.0 version of the 0.99.x branch

**Closed by JelteF** 2024-07-01 15:14 UTC

**Comment by JelteF** [comment] 2024-08-08 07:04
1.0.0 has been released!

Discussion: https://www.reddit.com/r/rust/comments/1emi4fi/comment/lh0jdm2/?%24deep_link=true&correlation_id=972c7015-daa8-4071-8cf0-e35fdd2bd913&ref=email_post_reply&ref_campaign=email_post_reply&ref_source=email&%243p=e_as&utm_medium=Email+Amazon+SES

Release: https://github.com/JelteF/derive_more/releases/tag/v1.0.0
